on:
  push:
    tags:
      - "v*"

name: Build Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build the artifacts
        run: make NAME=xraysub

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'bin/*'
